---
title: "viz_mariano_a4_task3"
author: "Mariano Viz"
date: "06/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(boot)
library(broom)

```





```{r}
#Vector of UCSB community members identified as nonbinary/genderqueer responds:
  ## n = 36
  ## 22/36 = "1" (personally experienced “exclusionary, offensive, hostile or intimidating conduct”)
  ##14/36 = "0" (didn't experience “exclusionary, offensive, hostile or intimidating conduct”)

ucsb_resp <- rep(c(1, 0),times=c(22, 14)) 


```


```{r}
#Create a function that calculates the proportion of UCSB community members identified as nonbinary/genderqueer who responded that they had personally experienced “exclusionary, offensive, hostile or intimidating conduct”

prop <- function (x, i) {
  sum(x[i])/length(x[i])
}


##Test function:
#prop(ucsb_resp)
   #result = 0.61


```




```{r}
# Create 100,000 bootstrap samples by resampling ucsb_resp vector and use the prop() function to calculate the respond proportions on each:

ucsb_resp_100k <- boot(ucsb_resp, 
                       statistic = prop, 
                       R = 100000)
  
# Check the output:  
#ucsb_resp_100k


```




```{r}
#Histogram of bootsrapped proportions:

## Make a data frame with the vectors of bootstrap sample proportions: 
ucsb_resp_100k_df <- data.frame(uscb_resp_prop = ucsb_resp_100k$t)

## Histogram plot:
 ggplot(data = ucsb_resp_100k_df, aes(x = uscb_resp_prop)) +
  geom_histogram(bins = 25) +
   theme_minimal()

```


```{r}
#Use bootstrapped sampling distribution to find the confidence interval:

ucsb_resp_100k_ci <- boot.ci(ucsb_resp_100k, conf = 0.95)

#in line reference:
ucsb_resp_100k_ci$normal[2]
```
A final statement (in text) describing the bootstrapped CI in the context of the data (suitable for publication).


A reminder on what a confidence interval means: For a 95% confidence interval, that means we expect that 95 of 100 calculated confidence intervals will contain the actual population parameter. 




